
### Path settings
path:
  expname: nerf2-rfid-knn
  datadir: data/s23/
  logdir: logs/s23/


### rendering settings
render:
  scale_worldsize: 1
  mode: 'spectrum'
  near: 0
  far: 5
  n_samples: 64


### training settings
train:
  lr: 8e-4
  weight_decay: 5e-5
  T_max: 10000
  eta_min: 1e-6
  batch_size: 8192
  total_iterations: 10000
  load_ckpt: True

  save_freq: 100
  val_freq: 2500
  report_freq: 100


### network settings
networks:
  D: 8
  W: 256
  skips: [4]
  is_embeded: True
  multires_pts: 10
  multires_view: 10
  multires_tx: 10



